apiVersion: v1
kind: Namespace
metadata:
  name: cafe-boreal
---
apiVersion: v1
kind: Secret
metadata:
  name: customers-secret
  namespace: cafe-boreal
type: Opaque
stringData:
  ENCRYPTION_KEY: "boreal_secret_key_256bit_32B_len!"
  DB_PASSWORD: "boreal_pass_256bit_secure"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: boreal-config
  namespace: cafe-boreal
data:
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_USER: "boreal_user"
  DB_NAME: "boreal_db"
  ANTI_FRAUD_PHRASE: "Café de Altura, Calidad de Origen y Tradición Boreal 2026"
